name: terraform-fmt
run-name: terraform action ${{ github.event.pull_request.title }}
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Perform Terraform Formatting Check
        run: |
          terraform fmt -check -recursive -diff
